-- MySQL Script generated by MySQL Workbench
-- 06/25/15 14:39:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema threela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema threela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `threela` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `threela` ;

-- -----------------------------------------------------
-- Table `threela`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`company` (
  `StockId` VARCHAR(10) NOT NULL COMMENT '',
  `ComName` NVARCHAR(100) NOT NULL COMMENT '',
  `Address` NVARCHAR(255) NULL COMMENT '',
  `Lat` DECIMAL(10,6) NULL COMMENT '',
  `Lon` DECIMAL(10,6) NULL COMMENT '',
  `geom` GEOMETRY NULL COMMENT '',
  PRIMARY KEY (`StockId`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `threela`.`trading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`trading` (
  `StockId` VARCHAR(10) NOT NULL COMMENT '',
  `Date` DATE NOT NULL COMMENT '',
  `OpenPrice` DOUBLE NULL COMMENT '',
  `ClosePrice` DOUBLE NULL COMMENT '',
  `HighPrice` DOUBLE NULL COMMENT '',
  `LowPrice` DOUBLE NULL COMMENT '',
  `Volume` INT NULL COMMENT '',
  `YieldRate` DOUBLE NULL COMMENT '',
  `PE` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`StockId`,`Date`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `threela`.`ROE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`ROE` (  
  `StockId` VARCHAR(10) NOT NULL COMMENT '',
  `Year` INT NOT NULL COMMENT '',
  `Season` INT NOT NULL COMMENT '',
  `BookValue` DOUBLE NULL COMMENT '',
  `EPS` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`StockId`,`Year`,`Season`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `threela`.`Revenue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`Revenue` (  
  `StockId` VARCHAR(10) NOT NULL COMMENT '',
  `Year` INT NOT NULL COMMENT '',
  `Month` INT NOT NULL COMMENT '',
  `MonthRev` INT NULL COMMENT '',
  `RevGrowthRate` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`StockId`,`Year`,`Month`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `threela`.`brokers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`brokers` (
  `BrokerId` VARCHAR(10) BINARY NOT NULL COMMENT '',
  `Name` NVARCHAR(100) NOT NULL COMMENT '',
  `Address` NVARCHAR(255) NULL COMMENT '',
  `Phone` VARCHAR(50) NULL COMMENT '',
  `FullTitle` NVARCHAR(100) NULL COMMENT '',
  `County` NVARCHAR(10) NULL COMMENT '',
  `Lat` DECIMAL(10,6) NULL COMMENT '',
  `Lon` DECIMAL(10,6) NULL COMMENT '',
  `HeadId` VARCHAR(10) NOT NULL COMMENT '',
  `geom` GEOMETRY NULL COMMENT '',
  PRIMARY KEY (`BrokerId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `threela`.`headbrokers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`headbrokers` (
  `HeadId` VARCHAR(10) NOT NULL COMMENT '',
  `Name` NVARCHAR(100) NULL COMMENT '',
  `OpenDate` DATE NULL COMMENT '',
  `Address` NVARCHAR(255) NULL COMMENT '',
  `FullTitle` NVARCHAR(100) NULL COMMENT '',
  `Phone` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`HeadId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `threela`.`daily`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`daily` (  
  `StockId` VARCHAR(10) NOT NULL COMMENT '',
  `BrokerId` VARCHAR(10) BINARY NOT NULL COMMENT '',
  `Date` DATE NOT NULL COMMENT '',
  `Buy` INT NULL COMMENT '',
  `Sell` INT NULL COMMENT '',
  `BuyPrice` DOUBLE NULL COMMENT '',
  `SellPrice` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`StockId`,`BrokerId`,`Date`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
