-- MySQL Script generated by MySQL Workbench
-- 06/25/15 14:39:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema threela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema threela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `threela` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `threela` ;

-- -----------------------------------------------------
-- Table `threela`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`company` (
  `StockId` VARCHAR(10) NOT NULL COMMENT '股票代號',
  `ComName` NVARCHAR(100) NOT NULL COMMENT '公司名稱',
  `Address` NVARCHAR(255) NULL COMMENT '地址',
  `Lat` DECIMAL(10,6) NULL COMMENT '緯度',
  `Lon` DECIMAL(10,6) NULL COMMENT '經度',
  `geom` GEOMETRY NULL COMMENT 'location',
  PRIMARY KEY (`StockId`)  COMMENT '股票代號')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `threela`.`trading`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`trading` (
  `StockId` VARCHAR(10) NOT NULL COMMENT '股票代號',
  `TimeId` INT NOT NULL COMMENT '交易日期',
  `OpenPrice` DOUBLE NULL COMMENT '開盤價格',
  `ClosePrice` DOUBLE NULL COMMENT '收盤價格',
  `HighPrice` DOUBLE NULL COMMENT '最高價格',
  `LowPrice` DOUBLE NULL COMMENT '最低價格',
  `Volume` INT NULL COMMENT '成交量(股數)',
  `YieldRate` DOUBLE NULL COMMENT '殖利率',
  `PE` DOUBLE NULL COMMENT '本益比',
  PRIMARY KEY (`StockId`,`TimeId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `threela`.`ROE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`ROE` (  
  `StockId` VARCHAR(10) NOT NULL COMMENT '',
  `Year` INT NOT NULL COMMENT '',
  `Season` INT NOT NULL COMMENT '',
  `BookValue` DOUBLE NULL COMMENT '股票淨值',
  `EPS` DOUBLE NULL COMMENT '每股盈餘',
  `DebtRatio` DOUBLE NULL COMMENT '負債比例',
  PRIMARY KEY (`StockId`,`Year`,`Season`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `threela`.`Revenue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`Revenue` (  
  `StockId` VARCHAR(10) NOT NULL COMMENT '',
  `Year` INT NOT NULL COMMENT '',
  `Month` INT NOT NULL COMMENT '',
  `MonthRev` INT NULL COMMENT '',
  `RevGrowthRate` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`StockId`,`Year`,`Month`)  COMMENT '')
ENGINE = InnoDB
CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `threela`.`brokers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`brokers` (
  `BrokerId` VARCHAR(10) BINARY NOT NULL COMMENT '',
  `Name` NVARCHAR(100) NOT NULL COMMENT '',
  `Address` NVARCHAR(255) NULL COMMENT '',
  `Phone` VARCHAR(50) NULL COMMENT '',  
  `CountyId` VARCHAR(10) NULL COMMENT '',
  `Lat` DECIMAL(10,6) NULL COMMENT '',
  `Lon` DECIMAL(10,6) NULL COMMENT '',
  `HeadId` VARCHAR(10) NOT NULL COMMENT '',
  `geom` GEOMETRY NULL COMMENT '',
  PRIMARY KEY (`BrokerId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `threela`.`headbrokers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`headbrokers` (
  `HeadId` VARCHAR(10) BINARY NOT NULL COMMENT '',
  `Name` NVARCHAR(100) NULL COMMENT '',
  `OpenDate` DATE NULL COMMENT '',
  `Address` NVARCHAR(255) NULL COMMENT '',
  `FullTitle` NVARCHAR(100) NULL COMMENT '',
  `Phone` VARCHAR(50) NULL COMMENT '',
  PRIMARY KEY (`HeadId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `threela`.`daily`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `threela`.`daily` (  
  `StockId` VARCHAR(10) NOT NULL COMMENT '',
  `BrokerId` VARCHAR(10) BINARY NOT NULL COMMENT '',
  `TimeId` int NOT NULL COMMENT '',
  `Buy` INT NULL COMMENT '',
  `Sell` INT NULL COMMENT '',
  `BuyPrice` DOUBLE NULL COMMENT '',
  `SellPrice` DOUBLE NULL COMMENT '',
  PRIMARY KEY (`StockId`,`BrokerId`,`TimeId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE table if not exists `threela`.`Time` (
	`TimeId` INT NOT NULL COMMENT '',
    `Year` INT Not NULL COMMENT '',
	`Month` INT Not NULL COMMENT '',
    `Day` INT NOT NULL COMMENT '',
    `Week` INT NOT NULL COMMENT '',
    `Date` Date not null
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE table if not exists `threela`.`County` (
	`CountyId` varchar(10) NOT NULL COMMENT '',
    `Name` nvarchar(10) Not NULL COMMENT ''
	
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
